spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 ??? DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  h2:
    console:
      enabled: true  # H2 ?? ???
  sql:
    init:
      mode: always


